{0.00000} <init Client> [INFO]:	(Logging enabled)
{0.00000} <init Client> [STATUS]:	(Venter på forbindelse på 0.0.0.0:12345...)
{44.92739} <init Client> [STATUS]:	(Forbundet til: ('192.168.28.151', 37728))
{44.92739} <init Client> [STATUS]:	(Modtaget EV3 is ready)
{45.80540} <Class Car Valid> [ERROR]:	(invalid triangle points, area too small: 0.5)
{45.80640} <unkown> [DEBUG]:	(generating invalid car, [<classes.Point object at 0x000002B6E59CE840>, <classes.Point object at 0x000002B6E59CE8D0>, <classes.Point object at 0x000002B6E59CE8A0>]; Point[0,0] Class car constructor)
{45.80740} <client Loop> [STATUS]:	(generating frame)
{45.86801} <update track> [DEBUG]:	(updating walls)
{46.21471} <update track> [DEBUG]:	(found 2 goals)
{46.21492} <update track> [DEBUG]:	(updating targets)
{46.24339} <update track> [DEBUG]:	(updating obsticles)
{46.26331} <update track> [DEBUG]:	(updating car)
{46.29564} <Class Car Valid> [INFO]:	(valid triangle points)
{46.29564} <Class Car Valid> [INFO]:	(area: 2956.0)
{46.29564} <Class Car Valid> [INFO]:	(valid triangle points)
{46.29564} <Class Car Valid> [INFO]:	(area: 2956.0)
{46.29564} <update track> [DEBUG]:	(car updated with 3 points)
{46.29866} <Class Car Valid> [INFO]:	(valid triangle points)
{46.29866} <Class Car Valid> [INFO]:	(area: 2956.0)
{46.29866} <Class Car Valid> [INFO]:	(valid triangle points)
{46.29965} <Class Car Valid> [INFO]:	(area: 2956.0)
{46.29965} <Class Car Valid> [INFO]:	(valid triangle points)
{46.29965} <Class Car Valid> [INFO]:	(area: 2956.0)
{46.29965} <Class Car Valid> [INFO]:	(valid triangle points)
{46.29965} <Class Car Valid> [INFO]:	(area: 2956.0)
{46.29965} <Class Car Valid> [INFO]:	(valid triangle points)
{46.29965} <Class Car Valid> [INFO]:	(area: 2956.0)
{46.30165} <client cleanup> [ERROR]:	(An error occurred: ['ValueError: max() iterable argument is empty\n'])
{46.30564} <client cleanup> [ERROR]:	(Stack trace: ['  File "c:\\Users\\chapp\\anaconda3\\Lib\\runpy.py", line 198, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n', '  File "c:\\Users\\chapp\\anaconda3\\Lib\\runpy.py", line 88, in _run_code\n    exec(code, run_globals)\n', '  File "c:\\Users\\chapp\\.vscode\\extensions\\ms-python.debugpy-2025.8.0-win32-x64\\bundled\\libs\\debugpy\\launcher/../..\\debugpy\\__main__.py", line 71, in <module>\n    cli.main()\n', '  File "c:\\Users\\chapp\\.vscode\\extensions\\ms-python.debugpy-2025.8.0-win32-x64\\bundled\\libs\\debugpy\\launcher/../..\\debugpy/..\\debugpy\\server\\cli.py", line 501, in main\n    run()\n', '  File "c:\\Users\\chapp\\.vscode\\extensions\\ms-python.debugpy-2025.8.0-win32-x64\\bundled\\libs\\debugpy\\launcher/../..\\debugpy/..\\debugpy\\server\\cli.py", line 351, in run_file\n    runpy.run_path(target, run_name="__main__")\n', '  File "c:\\Users\\chapp\\.vscode\\extensions\\ms-python.debugpy-2025.8.0-win32-x64\\bundled\\libs\\debugpy\\_vendored\\pydevd\\_pydevd_bundle\\pydevd_runpy.py", line 310, in run_path\n    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)\n', '  File "c:\\Users\\chapp\\.vscode\\extensions\\ms-python.debugpy-2025.8.0-win32-x64\\bundled\\libs\\debugpy\\_vendored\\pydevd\\_pydevd_bundle\\pydevd_runpy.py", line 127, in _run_module_code\n    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)\n', '  File "c:\\Users\\chapp\\.vscode\\extensions\\ms-python.debugpy-2025.8.0-win32-x64\\bundled\\libs\\debugpy\\_vendored\\pydevd\\_pydevd_bundle\\pydevd_runpy.py", line 118, in _run_code\n    exec(code, run_globals)\n', '  File "robot_client_controller.py", line 205, in <module>\n    printLog("ERROR", "Stack trace:", traceback.format_stack(),producer="client cleanup")\n'])
{46.30564} <client cleanup> [STATUS]:	(Closing connection without error)
{46.30664} <client cleanup> [STATUS]:	(Client socket closed)
{46.30664} <client cleanup> [STATUS]:	(Server socket closed)
{46.30664} <client cleanup> [STATUS]:	(closing log)
